### ISSUE TITLE
create token issue

### ISSUE THREAD

**Issue by GalvinLee** [Tonpad/bug-tracker#1]
*
![IMG_20240430_192602_864](https://github.com/Tonpad/bug-tracker/assets/168549349/30df8f56-46cc-4d59-bc1b-cd9c007ccc3f)

**Comment by 0xvictorb** [comment]
The error above is from the Tonkeeper wallet, it could be due to an insufficient TON testnet balance. 
Follow the steps mentioned in the guide https://tonpad.substack.com/p/tonpad-testnet-guide to top up your balance and try again.

**Comment by 0xvictorb** [comment]
I’ll closing this issue as the bug is not on our side. Feel free to reopen if you face the same problem again.
