### ISSUE TITLE
Token Publish always lagging 

### ISSUE THREAD

**Issue by Emdaud** [Tonpad/bug-tracker#4]
**Describe the bug**
Whenever you want to publish a token and make payments it keeps taking you back until after 6 trials before it gets approved 
This information keeps popping up
![IMG-20240503-WA0030](https://github.com/Tonpad/bug-tracker/assets/97974393/6a3ff209-9b83-4503-be49-3274322fce2f)

**Comment by 0xvictorb** [comment]
Hi @Emdaud ,
Thanks for reporting the issue. This is a bug on our end that occurs when the listing price is too high, the same issue as #2. We are currently working on fixing this bug and will let you know once it is resolved.

In the meantime, you can try creating a launchpad by reducing the listing price to a smaller value, ex: 1 TON.

**Comment by 0xvictorb** [comment]
@Emdaud  this bug has been fixed, I'll close this issue. Feel free to re-open it if you encountered this issue again.
