### ISSUE TITLE
Can't create new token

### ISSUE THREAD

**Issue by Ezechielthz** [Tonpad/bug-tracker#6]
**Describe the bug**
So whenever I try to create new token and confirm, tonkeeper keep telling me to fill in the password and nothing happen, and when I press confirm, it tells me to fill in the password and nothing will happen, and so on

**Your Wallet Address**
0QDP01mXzpuTzSWCgO2OKHJ1_-wW3CxiJvPW1Ik6Y6qsb6eY

**Test Environment**
(please complete the following information):
- Device: Laptop Acer Nitro 5
 - OS: i5-11400H 2.70GHz
 - Wallet name: Tonkeeper
 - Environment: Web using Tonkeeper extension
 - Version: 22H2

**To Reproduce**
1. Go to 'Token Tools'
2. Click on 'Create Token'
3. Fill in the information
4. Click 'Create Token'
5. See error

**Expected behavior**
Tonkeeper not processing the confirmation

**Screenshots**
No screenshot because no error showed but It just doesn't process it

**Comment by 0xvictorb** [comment]
Hi @Ezechielthz, thanks for reporting the issue.
The error was due to the TON Blockchain Testnet unstable recently. 
We've contacted the Tonkeeper team and will get back to you when it's up and running again.

**Comment by 0xvictorb** [comment]
@Ezechielthz the TON Testnet is up now, you should able to create token without any problems.
Feel free to re-open it if the issue happen again.

**Comment by Ezechielthz** [comment]
This issue happens again
